/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;


import controller.PersonalGoalController;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import dao.PersonalGoalDao;
import dao.PersonalGoalPathDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/*
 ** Μια φόρμα που υλοποιή το μοντέλου του Προσωπικού στόχου (Personal Goal)
 *@author alex
 */
public class PersonalGoalForm extends javax.swing.JFrame implements IPersonalGoalForm{
    private PersonalGoalController PersonalGoalController;
    private final String database = "alexis.txt";
   

    /**
     * Creates new form PersonalGoalForm
     */
    public PersonalGoalForm() {
        initComponents();
      //  PersonalGoalDao db = new PersonalGoalDao();
     //         db.loadDatabase(database);
    }
    
    public PersonalGoalForm(String txt) {
        initComponents();
      
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        withPersonLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        withPersonTextField = new javax.swing.JTextField();
        WhenDate = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementEditorPane = new javax.swing.JEditorPane();
        AnnouncementLabel = new javax.swing.JLabel();
        whenDateSpinner = new javax.swing.JSpinner();
        addNewFotoLabel = new javax.swing.JLabel();
        browseFotoFile = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        browseFotoTextField = new javax.swing.JTextField();
        buttonUploadFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("New Personal Goal");

        titleLabel.setText("Title:");

        locationLabel.setText("Location:");

        withPersonLabel.setText("With Person:");

        WhenDate.setText("WhenDate");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(announcementEditorPane);

        AnnouncementLabel.setText("Announcement");

        whenDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        whenDateSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        whenDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(whenDateSpinner, "dd/MM/yyyy"));

        addNewFotoLabel.setText("UPLOAD YOUR FOTO");
        addNewFotoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        browseFotoFile.setText("Browse..");
        browseFotoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFotoFileActionPerformed(evt);
            }
        });

        imageLabel.setToolTipText("");
        imageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        browseFotoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFotoTextFieldActionPerformed(evt);
            }
        });

        buttonUploadFoto.setText("Upload");
        buttonUploadFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUploadFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(locationLabel)
                    .addComponent(withPersonLabel)
                    .addComponent(titleLabel)
                    .addComponent(WhenDate)
                    .addComponent(AnnouncementLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(51, 51, 51)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(whenDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(locationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(titleTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(withPersonTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(browseFotoFile)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonUploadFoto)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addNewFotoLabel)
                                        .addContainerGap(142, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(browseFotoTextField)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLabel)
                            .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withPersonLabel)
                            .addComponent(withPersonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WhenDate)
                            .addComponent(whenDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnnouncementLabel)
                                .addGap(0, 181, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cancelButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addNewFotoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(browseFotoFile)
                            .addComponent(buttonUploadFoto))
                        .addGap(32, 32, 32)
                        .addComponent(browseFotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * cancelButton για να γίνει close η φόρμα.
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
  
    /**
     * saveButton για να γίνεται τυχόν έλενχος πεδίον και το τελικό save. 
     * @param evt 
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            
           PersonalGoalController newController = new PersonalGoalController();
           newController.createPersonalGoal(titleTextField.getText(),locationTextField.getText(),withPersonTextField.getText(),whenDateSpinner.getValue().toString(),announcementEditorPane.getText());
            
                              
     
        } catch (Exception ex) {
            Logger.getLogger(PersonalGoalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_saveButtonActionPerformed

    //FIXME: refactor  σε μια νέα κλάση 
    /**
     * 
     * @param fileDescription
     * @param fileSuffixes
     * @param dialog
     * @return 
     */
    private File getFile(String fileDescription, String[] fileSuffixes, String dialog )
    {
        JFileChooser f = new JFileChooser();
        f.setFileFilter( new FileNameExtensionFilter(fileDescription,fileSuffixes)); 
        f.setAcceptAllFileFilterUsed(false);
        if(f.showDialog(this, dialog) == JFileChooser.CANCEL_OPTION )
            return null;
        else
            return f.getSelectedFile();
    }
     //FIXME: refactor  σε μια νέα κλάση 
    /**
     * 
     * @param evt 
     */
    private void browseFotoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFotoFileActionPerformed

        File file = getFile("Image", ImageIO.getReaderFileSuffixes(), "Select");
        if(file != null)
            browseFotoTextField.setText(file.getAbsolutePath());

    }//GEN-LAST:event_browseFotoFileActionPerformed
/**
 * 
 * @param evt 
 */
    private void browseFotoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFotoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browseFotoTextFieldActionPerformed
      
     //FIXME: refactor  σε μια νέα κλάση 
    /**
     * buttonUpload για να εμφανίζεται η εικόνα μέσα στην φόρμα.
     * @param evt 
     */
    private void buttonUploadFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadFotoActionPerformed
           
           String fileName = browseFotoTextField.getText();
           if(fileName.equals(""))
               System.out.println("Error[buttonUpload()]: File not selected");
           else
           {
               File file = new File(fileName);
               if(file == null)
                   System.out.println("Error[buttonUpload()]: Can not load file");
               else
               {
                    BufferedImage img = null;
                    try {
                        img = ImageIO.read(file);
                    } catch (IOException e) {
                        System.out.println("Error[ddButtonActionPerformed()] Can not add image");    
                    }
                    int w = imageLabel.getWidth();
                    int h = imageLabel.getHeight();

                    int type = img.getType() == 0? BufferedImage.TYPE_INT_ARGB : img.getType();

                    BufferedImage resizedImg = new BufferedImage(w, h, type);
                    Graphics g = resizedImg.createGraphics();
                    g.drawImage(img, 0, 0, w, h, null);
                    g.dispose();
                    imageLabel.setIcon(new ImageIcon(resizedImg));
               } 
           }
    }//GEN-LAST:event_buttonUploadFotoActionPerformed
    //FIXME: refactor  σε μια νέα κλάση και να βάλω interface
    // displayErrorMessage εαν υπάρχει κάποιο λάθος.
    @Override
       public void displayErrorMessage(String errorMessage)
    {
        JOptionPane.showMessageDialog(this, errorMessage);
    }
     @Override  
          public void displaySuccessMessage(String successMessage)
    {
        JOptionPane.showMessageDialog(this, successMessage);
    }
       
      
       
      public class Utils {

    public final static String jpeg = "jpeg";
    public final static String jpg = "jpg";
    public final static String gif = "gif";
    public final static String tiff = "tiff";
    public final static String tif = "tif";
    public final static String png = "png";

   
} 
      
    /**
     * @param args the command line arguments
     * @throws java.io.UnsupportedEncodingException
     */
    public static void main(String args[]) throws UnsupportedEncodingException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalGoalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PersonalGoalForm().setVisible(true);
            }
        });
        
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnnouncementLabel;
    private javax.swing.JLabel WhenDate;
    private javax.swing.JLabel addNewFotoLabel;
    private javax.swing.JEditorPane announcementEditorPane;
    private javax.swing.JButton browseFotoFile;
    private javax.swing.JTextField browseFotoTextField;
    private javax.swing.JButton buttonUploadFoto;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JSpinner whenDateSpinner;
    private javax.swing.JLabel withPersonLabel;
    private javax.swing.JTextField withPersonTextField;
    // End of variables declaration//GEN-END:variables
    private BufferedImage dialogImage;
    private PersonalGoalDao db;
}
